 var Exp4_Respy = [
           {ac: "GoToGate", x: 80, y: 51, map: "Ruiny Szabrowników"},
              {ac: "Attack", target: "Królik", map: "Ruiny Szabrowników"},
     ]
    var Exp3_Respy = [
      {ac: "GoToGate", x: 47, y: 63, map: "Torneg"},
      {ac: "GoToGate", x: 76, y: 64, map: "Stare Ruiny"},
      {ac: "GoToGate", x: 63, y: 79, map: "Dziewicza Knieja"},
         {ac: "GoTo", x: 3, y: 78, map: "Las Tropicieli"},
         {ac: "Attack", target: "Leśny bazyliszek", map: "Las Tropicieli"},
         {ac: "GoTo", x: 11, y: 82, map: "Las Tropicieli"},
         {ac: "Attack", target: "Ziemny bazyliszek", map: "Las Tropicieli"},
         {ac: "GoTo", x: 15, y: 84, map: "Las Tropicieli"},
         {ac: "Attack", target: "Leśny bazyliszek", map: "Las Tropicieli"},
         {ac: "GoTo", x: 16, y: 89, map: "Las Tropicieli"},
         {ac: "Attack", target: "Kamienny bazyliszek", map: "Las Tropicieli"},
         {ac: "GoTo", x: 18, y: 88, map: "Las Tropicieli"},
         {ac: "Attack", target: "Leśny bazyliszek", map: "Las Tropicieli"},
         {ac: "GoTo", x: 9, y: 91, map: "Las Tropicieli"},
         {ac: "Attack", target: "Ziemny bazyliszek", map: "Las Tropicieli"},
         {ac: "GoTo", x: 31, y: 86, map: "Las Tropicieli"},
         {ac: "Attack", target: "Kamienny bazyliszek", map: "Las Tropicieli"},
         {ac: "GoTo", x: 38, y: 91, map: "Las Tropicieli"},
         {ac: "Attack", target: "Szlachetny bazyliszek", map: "Las Tropicieli"},
         {ac: "GoTo", x: 48, y: 88, map: "Las Tropicieli"},
         {ac: "Attack", target: "Kamienny bazyliszek", map: "Las Tropicieli"},
         {ac: "GoTo", x: 55, y: 89, map: "Las Tropicieli"},
         {ac: "Attack", target: "Kamienny bazyliszek", map: "Las Tropicieli"},
         {ac: "GoTo", x: 18, y: 73, map: "Las Tropicieli"},
         {ac: "Attack", target: "Ziemny bazyliszek", map: "Las Tropicieli"},
         {ac: "GoTo", x: 25, y: 68, map: "Las Tropicieli"},
         {ac: "Attack", target: "Ziemny bazyliszek", map: "Las Tropicieli"},
         {ac: "GoTo", x: 21, y: 63, map: "Las Tropicieli"},
         {ac: "Attack", target: "Leśny bazyliszek ", map: "Las Tropicieli"},
         {ac: "GoTo", x: 13, y: 63, map: "Las Tropicieli"},
         {ac: "Attack", target: "Ziemny bazyliszek", map: "Las Tropicieli"},
         {ac: "GoTo", x: 10, y: 65, map: "Las Tropicieli"},
         {ac: "Attack", target: "Leśny bazyliszek", map: "Las Tropicieli"},
         {ac: "GoTo", x: 7, y: 60, map: "Las Tropicieli"},
         {ac: "Attack", target: "Kamienny bazyliszek", map: "Las Tropicieli"},
         {ac: "GoTo", x: 12, y: 55, map: "Las Tropicieli"},
         {ac: "Attack", target: "Leśny bazyliszek", map: "Las Tropicieli"},
         {ac: "GoTo", x: 17, y: 50, map: "Las Tropicieli"},
         {ac: "Attack", target: "Szlachetny bazyliszek", map: "Las Tropicieli"},
         {ac: "GoTo", x: 21, y: 35, map: "Las Tropicieli"},
         {ac: "Attack", target: "Leśny bazyliszek", map: "Las Tropicieli"},
         {ac: "GoTo", x: 13, y: 35, map: "Las Tropicieli"},
         {ac: "Attack", target: "Kamienny bazyliszek", map: "Las Tropicieli"},
         {ac: "GoTo", x: 26, y: 32, map: "Las Tropicieli"},
         {ac: "Attack", target: "Ziemny bazyliszek", map: "Las Tropicieli"},
         {ac: "GoTo", x: 31, y: 39, map: "Las Tropicieli"},
         {ac: "Attack", target: "Leśny bazyliszek", map: "Las Tropicieli"},
         {ac: "GoTo", x: 25, y: 51, map: "Las Tropicieli"},
         {ac: "Attack", target: "Kamienny bazyliszek", map: "Las Tropicieli"},
         {ac: "GoTo", x: 35, y: 57, map: "Las Tropicieli"},
         {ac: "Attack", target: "Leśny bazyliszek", map: "Las Tropicieli"},
         {ac: "GoTo", x: 35, y: 61, map: "Las Tropicieli"},
         {ac: "Attack", target: "Szlachetny bazyliszek", map: "Las Tropicieli"},
         {ac: "GoTo", x: 52, y: 60, map: "Las Tropicieli"},
         {ac: "Attack", target: "Ziemny bazyliszek", map: "Las Tropicieli"},
         {ac: "GoTo", x: 56, y: 53, map: "Las Tropicieli"},
         {ac: "Attack", target: "Kamienny bazyliszek", map: "Las Tropicieli"},
         {ac: "GoTo", x: 57, y: 43, map: "Las Tropicieli"},
         {ac: "Attack", target: "Kamienny bazyliszek", map: "Las Tropicieli"},
         {ac: "GoTo", x: 46, y: 46, map: "Las Tropicieli"},
         {ac: "Attack", target: "Ziemny bazyliszek", map: "Las Tropicieli"},
         {ac: "GoTo", x: 60, y: 34, map: "Las Tropicieli"},
         {ac: "Attack", target: "Kamienny bazyliszek", map: "Las Tropicieli"},
         {ac: "GoTo", x: 60, y: 21, map: "Las Tropicieli"},
         {ac: "Attack", target: "Ziemny bazyliszek", map: "Las Tropicieli"},
         {ac: "GoTo", x: 54, y: 28, map: "Las Tropicieli"},
         {ac: "Attack", target: "Ziemny bazyliszek", map: "Las Tropicieli"},
         {ac: "GoTo", x: 47, y: 25, map: "Las Tropicieli"},
         {ac: "Attack", target: "Leśny bazyliszek", map: "Las Tropicieli"},
         {ac: "GoTo", x: 35, y: 17, map: "Las Tropicieli"},
         {ac: "Attack", target: "Kamienny bazyliszek", map: "Las Tropicieli"},
         {ac: "GoTo", x: 28, y: 14, map: "Las Tropicieli"},
         {ac: "Attack", target: "Ziemny bazyliszek", map: "Las Tropicieli"},
         {ac: "GoTo", x: 17, y: 15, map: "Las Tropicieli"},
         {ac: "Attack", target: "Ziemny bazyliszek", map: "Las Tropicieli"},
         {ac: "GoTo", x: 13, y: 11, map: "Las Tropicieli"},
         {ac: "Attack", target: "Leśny bazyliszek", map: "Las Tropicieli"},
         {ac: "Reset", number: 4, map: "Las Tropicieli"},
   ]

 var Exp1_Respy = [
        {ac: "GoToGate", x: 47, y: 63, map: "Torneg"},
        {ac: "GoToGate", x: 43, y:  63, map: "Stare Ruiny"},
        {ac: "GoToGate", x: 53, y: 24, map: "Orla Grań"},
        {ac: "GoTo", x: 11, y: 19, map: "Przeklęta Strażnica"},
        {ac: "Attack", target: "Paskudny Demon", map: "Przeklęta Strażnica"},
        {ac: "GoTo", x: 10, y: 18, map: "Przeklęta Strażnica"},
        {ac: "Attack", target: "Pomniejszy demon", map: "Przeklęta Strażnica"},
        {ac: "GoTo", x: 13, y: 13, map: "Przeklęta Strażnica"},
        {ac: "Attack", target: "Nieznośny demon", map: "Przeklęta Strażnica"},
        {ac: "GoTo", x: 17, y: 14, map: "Przeklęta Strażnica"},
        {ac: "Attack", target: "Nieznośny demon", map: "Przeklęta Strażnica"},
        {ac: "GoTo", x: 17, y: 11, map: "Przeklęta Strażnica"},
        {ac: "Attack", target: "Mały demon", map: "Przeklęta Strażnica"},
        {ac: "GoTo", x: 10, y: 8, map: "Przeklęta Strażnica"},
        {ac: "Attack", target: "Mały demon", map: "Przeklęta Strażnica"},
        {ac: "GoTo", x: 7, y: 9, map: "Przeklęta Strażnica"},
        {ac: "Attack", target: "Nieznośny demon", map: "Przeklęta Strażnica"},
        {ac: "GoTo", x: 4, y: 14, map: "Przeklęta Strażnica"},
        {ac: "Attack", target: "Mały demon", map: "Przeklęta Strażnica"},
        {ac: "GoToGate", x: 2, y: 16, map: "Przeklęta Strażnica"},
        {ac: "GoTo", x: 18, y: 8, map: "Przeklęta Strażnica - podziemia p.1 s.1"},
        {ac: "Attack", target: "Nieznośny demon", map: "Przeklęta Strażnica - podziemia p.1 s.1"},
        {ac: "GoTo", x: 20, y: 11, map: "Przeklęta Strażnica - podziemia p.1 s.1"},
        {ac: "Attack", target: "Mały demon", map: "Przeklęta Strażnica - podziemia p.1 s.1"},
        {ac: "GoTo", x: 15, y: 10, map: "Przeklęta Strażnica - podziemia p.1 s.1"},
        {ac: "Attack", target: "Kąśliwy demon", map: "Przeklęta Strażnica - podziemia p.1 s.1"},
        {ac: "GoTo", x: 12, y: 10, map: "Przeklęta Strażnica - podziemia p.1 s.1"},
        {ac: "Attack", target: "Nieznośny demon", map: "Przeklęta Strażnica - podziemia p.1 s.1"},
        {ac: "GoTo", x: 9, y: 5, map: "Przeklęta Strażnica - podziemia p.1 s.1"},
        {ac: "Attack", target: "Paskudny demon", map: "Przeklęta Strażnica - podziemia p.1 s.1"},
        {ac: "GoTo", x: 4, y: 8, map: "Przeklęta Strażnica - podziemia p.1 s.1"},
        {ac: "Attack", target: "Mały demon", map: "Przeklęta Strażnica - podziemia p.1 s.1"},
        {ac: "GoTo", x: 16, y: 18, map: "Przeklęta Strażnica - podziemia p.1 s.1"},
        {ac: "Attack", target: "Mały demon", map: "Przeklęta Strażnica - podziemia p.1 s.1"},
        {ac: "GoTo", x: 14, y: 21, map: "Przeklęta Strażnica - podziemia p.1 s.1"},
        {ac: "Attack", target: "Nieznośny demon", map: "Przeklęta Strażnica - podziemia p.1 s.1"},
        {ac: "GoTo", x: 6, y: 23, map: "Przeklęta Strażnica - podziemia p.1 s.1"},
        {ac: "Attack", target: "Nieznośny demon", map: "Przeklęta Strażnica - podziemia p.1 s.1"},
        {ac: "GoTo", x: 17, y: 26, map: "Przeklęta Strażnica - podziemia p.1 s.1"},
        {ac: "Attack", target: "Pomniejszy demon", map: "Przeklęta Strażnica - podziemia p.1 s.1"},
        {ac: "GoTo", x: 22, y: 22, map: "Przeklęta Strażnica - podziemia p.1 s.1"},
        {ac: "Attack", target: "Nieznośny demon", map: "Przeklęta Strażnica - podziemia p.1 s.1"},
        {ac: "GoTo", x: 26, y: 22, map: "Przeklęta Strażnica - podziemia p.1 s.1"},
        {ac: "Attack", target: "Pomniejszy demon", map: "Przeklęta Strażnica - podziemia p.1 s.1"},
        {ac: "GoTo", x: 34, y: 22, map: "Przeklęta Strażnica - podziemia p.1 s.1"},
        {ac: "Attack", target: "Pomniejszy demon", map: "Przeklęta Strażnica - podziemia p.1 s.1"},
        {ac: "GoTo", x: 36, y: 25, map: "Przeklęta Strażnica - podziemia p.1 s.1"},
        {ac: "Attack", target: "Kąśliwy demon", map: "Przeklęta Strażnica - podziemia p.1 s.1"},
        {ac: "GoTo", x: 15, y: 35, map: "Przeklęta Strażnica - podziemia p.1 s.1"},
        {ac: "Attack", target: "Nieznośny demon", map: "Przeklęta Strażnica - podziemia p.1 s.1"},
        {ac: "GoTo", x: 12, y: 36, map: "Przeklęta Strażnica - podziemia p.1 s.1"},
        {ac: "Attack", target: "Dokuczliwy bies", map: "Przeklęta Strażnica - podziemia p.1 s.1"},
        {ac: "GoTo", x: 4, y: 35, map: "Przeklęta Strażnica - podziemia p.1 s.1"},
        {ac: "Attack", target: "Dokuczliwy bies", map: "Przeklęta Strażnica - podziemia p.1 s.1"},
        {ac: "GoTo", x: 8, y: 32, map: "Przeklęta Strażnica - podziemia p.1 s.1"},
        {ac: "Attack", target: "Pomniejszy demon", map: "Przeklęta Strażnica - podziemia p.1 s.1"},
        {ac: "GoTo", x: 21, y: 34, map: "Przeklęta Strażnica - podziemia p.1 s.1"},
        {ac: "Attack", target: "Dokuczliwy bies", map: "Przeklęta Strażnica - podziemia p.1 s.1"},
        {ac: "GoTo", x: 25, y: 35, map: "Przeklęta Strażnica - podziemia p.1 s.1"},
        {ac: "Attack", target: "Kąśliwy demon", map: "Przeklęta Strażnica - podziemia p.1 s.1"},
        {ac: "GoTo", x: 32, y: 35, map: "Przeklęta Strażnica - podziemia p.1 s.1"},
        {ac: "Attack", target: "Dokuczliwy bies", map: "Przeklęta Strażnica - podziemia p.1 s.1"},/// Nie skonczone, nie chce mi sie xD
        ]

var Exp2_Respy = [
        {ac: "GoToGate", x: 76, y: 64, map: "Stare Ruiny"},
        {ac: "GoToGate", x: 10, y: 42, map: "Dziewicza Knieja"},
        {ac: "GoTo", x: 5, y: 11, map: "Siedlisko Nietoperzy p.5"},
            {ac: "Attack", target: "Gacek szary", map: "Siedlisko Nietoperzy p.5"},
    {ac: "GoTo", x: 8, y: 9, map: "Siedlisko Nietoperzy p.5"},
            {ac: "Attack", target: "Gacek szary", map: "Siedlisko Nietoperzy p.5"},
    {ac: "GoToGate", x: 7, y: 11, map: "Siedlisko Nietoperzy p.5"},
    {ac: "GoTo", x: 7, y: 3, map: "Siedlisko Nietoperzy p.4"},
            {ac: "Attack", target: "Gacek szary", map: "Siedlisko Nietoperzy p.4"},
    {ac: "GoTo", x: 7, y: 4, map: "Siedlisko Nietoperzy p.4"},
            {ac: "Attack", target: "Gacek szary", map: "Siedlisko Nietoperzy p.4"},
    {ac: "GoTo", x: 8, y: 8, map: "Siedlisko Nietoperzy p.4"},
            {ac: "Attack", target: "Gacek szary", map: "Siedlisko Nietoperzy p.4"},
    {ac: "GoTo", x: 10, y: 12, map: "Siedlisko Nietoperzy p.4"},
            {ac: "Attack", target: "Gacek szary", map: "Siedlisko Nietoperzy p.4"},
    {ac: "GoToGate", x: 11, y: 14, map: "Siedlisko Nietoperzy p.4"},
    {ac: "GoTo", x: 9, y: 4, map: "Siedlisko Nietoperzy p.3 - sala 1"},
                {ac: "Attack", target: "Gacek szary", map: "Siedlisko Nietoperzy p.3 - sala 1"},
        {ac: "GoTo", x: 10, y: 9, map: "Siedlisko Nietoperzy p.3 - sala 1"},
                    {ac: "Attack", target: "Gacek szary", map: "Siedlisko Nietoperzy p.3 - sala 1"},
        {ac: "GoTo", x: 14, y: 9, map: "Siedlisko Nietoperzy p.3 - sala 1"},
                    {ac: "Attack", target: "Gacek szary", map: "Siedlisko Nietoperzy p.3 - sala 1"},
        {ac: "GoTo", x: 9, y: 15, map: "Siedlisko Nietoperzy p.3 - sala 1"},
                    {ac: "Attack", target: "Gacek szary", map: "Siedlisko Nietoperzy p.3 - sala 1"},
        {ac: "GoTo", x: 11, y: 23, map: "Siedlisko Nietoperzy p.3 - sala 1"},
                    {ac: "Attack", target: "Gacek szary", map: "Siedlisko Nietoperzy p.3 - sala 1"},
        {ac: "GoTo", x: 14, y: 26, map: "Siedlisko Nietoperzy p.3 - sala 1"},
                    {ac: "Attack", target: "Gacek szary", map: "Siedlisko Nietoperzy p.3 - sala 1"},
        {ac: "GoToGate", x: 21, y: 10, map: "Siedlisko Nietoperzy p.3 - sala 1"},
            {ac: "GoTo", x: 3, y: 29, map: "Siedlisko Nietoperzy p.3 - sala 2"},
     {ac: "Attack", target: "Gacek szary", map: "Siedlisko Nietoperzy p.3 - sala 2"},
                {ac: "GoTo", x: 9, y: 27, map: "Siedlisko Nietoperzy p.3 - sala 2"},
                        {ac: "Attack", target: "Gacek szary", map: "Siedlisko Nietoperzy p.3 - sala 2"},
                {ac: "GoTo", x: 11, y: 24, map: "Siedlisko Nietoperzy p.3 - sala 2"},
                            {ac: "Attack", target: "Gacek szary", map: "Siedlisko Nietoperzy p.3 - sala 2"},
                {ac: "GoTo", x: 18, y: 28, map: "Siedlisko Nietoperzy p.3 - sala 2"},
                            {ac: "Attack", target: "Gacek szary", map: "Siedlisko Nietoperzy p.3 - sala 2"},
                {ac: "GoTo", x: 18, y: 31, map: "Siedlisko Nietoperzy p.3 - sala 2"},
                            {ac: "Attack", target: "Gacek szary", map: "Siedlisko Nietoperzy p.3 - sala 2"},
                {ac: "GoTo", x: 27, y: 31, map: "Siedlisko Nietoperzy p.3 - sala 2"},
                            {ac: "Attack", target: "Gacek szary", map: "Siedlisko Nietoperzy p.3 - sala 2"},
                {ac: "GoTo", x: 17, y: 22, map: "Siedlisko Nietoperzy p.3 - sala 2"},
                            {ac: "Attack", target: "Gacek szary", map: "Siedlisko Nietoperzy p.3 - sala 2"},
                {ac: "GoTo", x: 13, y: 16, map: "Siedlisko Nietoperzy p.3 - sala 2"},
                            {ac: "Attack", target: "Gacek szary", map: "Siedlisko Nietoperzy p.3 - sala 2"},
                {ac: "GoTo", x: 13, y: 10, map: "Siedlisko Nietoperzy p.3 - sala 2"},
                            {ac: "Attack", target: "Paladyński Apostata", map: "Siedlisko Nietoperzy p.3 - sala 2"},
                {ac: "GoTo", x: 9, y: 10, map: "Siedlisko Nietoperzy p.3 - sala 2"},
                                            {ac: "Attack", target: "Gacek szary", map: "Siedlisko Nietoperzy p.3 - sala 2"},
                {ac: "GoTo", x: 9, y: 7, map: "Siedlisko Nietoperzy p.3 - sala 2"},
                                            {ac: "Attack", target: "Gacek szary", map: "Siedlisko Nietoperzy p.3 - sala 2"},
                {ac: "GoTo", x: 13, y: 6, map: "Siedlisko Nietoperzy p.3 - sala 2"},
                                            {ac: "Attack", target: "Gacek szary", map: "Siedlisko Nietoperzy p.3 - sala 2"},
                {ac: "GoTo", x: 21, y: 8, map: "Siedlisko Nietoperzy p.3 - sala 2"},
                                            {ac: "Attack", target: "Gacek szary", map: "Siedlisko Nietoperzy p.3 - sala 2"},
                {ac: "GoTo", x: 29, y: 6, map: "Siedlisko Nietoperzy p.3 - sala 2"},
                                            {ac: "Attack", target: "Gacek szary", map: "Siedlisko Nietoperzy p.3 - sala 2"},
                {ac: "GoTo", x: 23, y: 12, map: "Siedlisko Nietoperzy p.3 - sala 2"},
                                            {ac: "Attack", target: "Gacek szary", map: "Siedlisko Nietoperzy p.3 - sala 2"},
               {ac: "GoToGate", x: 2, y: 30, map: "Siedlisko Nietoperzy p.3 - sala 2"},
               {ac: "GoToGate", x: 17, y: 30, map: "Siedlisko Nietoperzy p.3 - sala 1"},
               {ac: "GoTo", x: 15, y: 5, map: "Siedlisko Nietoperzy p.2"},
    {ac: "Attack", target: "Gacek szary", map: "Siedlisko Nietoperzy p.2"},
               {ac: "GoTo", x: 16, y: 13, map: "Siedlisko Nietoperzy p.2"},
    {ac: "Attack", target: "Gacek szary", map: "Siedlisko Nietoperzy p.2"},
               {ac: "GoTo", x: 13, y: 17, map: "Siedlisko Nietoperzy p.2"},
    {ac: "Attack", target: "Gacek szary", map: "Siedlisko Nietoperzy p.2"},
                   {ac: "GoTo", x: 10, y: 17, map: "Siedlisko Nietoperzy p.2"},
    {ac: "Attack", target: "Gacek szary", map: "Siedlisko Nietoperzy p.2"},
                       {ac: "GoToGate", x: 11, y: 10, map: "Siedlisko Nietoperzy p.2"},
       {ac: "GoTo", x: 18, y: 13, map: "Siedlisko Nietoperzy p.1"},
    {ac: "Attack", target: "Gacek szary", map: "Siedlisko Nietoperzy p.1"},
        {ac: "GoTo", x: 16, y: 12, map: "Siedlisko Nietoperzy p.1"},
     {ac: "Attack", target: "Gacek szary", map: "Siedlisko Nietoperzy p.1"},
        {ac: "GoTo", x: 18, y: 13, map: "Siedlisko Nietoperzy p.1"},
     {ac: "Attack", target: "Gacek szary", map: "Siedlisko Nietoperzy p.1"},
        {ac: "GoTo", x: 17, y: 8, map: "Siedlisko Nietoperzy p.1"},
     {ac: "Attack", target: "Gacek szary", map: "Siedlisko Nietoperzy p.1"},
        {ac: "GoTo", x: 13, y: 14, map: "Siedlisko Nietoperzy p.1"},
     {ac: "Attack", target: "Gacek szary", map: "Siedlisko Nietoperzy p.1"},
        {ac: "GoTo", x: 11, y: 18, map: "Siedlisko Nietoperzy p.1"},
     {ac: "Attack", target: "Gacek szary", map: "Siedlisko Nietoperzy p.1"},
        {ac: "GoToGate", x: 7, y: 20, map: "Siedlisko Nietoperzy p.1"},
            {ac: "GoTo", x: 14, y: 65, map: "Dziewicza Knieja"},
                {ac: "Attack", target: "Niedźwiedź brunatny", map: "Dziewicza Knieja"},
    {ac: "GoToGate", x: 10, y: 42, map: "Dziewicza Knieja"},
          {ac: "Reset", number: 3, map: "Siedlisko Nietoperzy p.5"},
        ]

var Wilki_Respy = [
     {ac: "GoTo", x: 78, y: 41, map: "Stare Ruiny"},
        {ac: "Attack", target: "Szary wilk", map: "Stare Ruiny"},
        {ac: "GoTo", x: 70, y: 38, map: "Stare Ruiny"},
        {ac: "Attack", target: "Szary wilk", map: "Stare Ruiny"},
        {ac: "GoTo", x: 65, y: 45, map: "Stare Ruiny"},
        {ac: "Attack", target: "Szary wilk", map: "Stare Ruiny"},
        {ac: "GoTo", x: 52, y: 43, map: "Stare Ruiny"},
        {ac: "Attack", target: "Czarny wilk", map: "Stare Ruiny"},
        {ac: "GoTo", x: 52, y: 47, map: "Stare Ruiny"},
        {ac: "Attack", target: "Szary wilk", map: "Stare Ruiny"},
        {ac: "GoTo", x: 69, y: 54, map: "Stare Ruiny"},
        {ac: "Attack", target: "Szary wilk", map: "Stare Ruiny"},
        {ac: "GoTo", x: 77, y: 59, map: "Stare Ruiny"},
        {ac: "Attack", target: "Szary wilk", map: "Stare Ruiny"},
        {ac: "GoTo", x: 78, y: 52, map: "Stare Ruiny"},
        {ac: "Attack", target: "Czarny wilk", map: "Stare Ruiny"},
        {ac: "GoTo", x: 78, y: 48, map: "Stare Ruiny"},
        {ac: "Attack", target: "Szary wilk", map: "Stare Ruiny"},
        {ac: "GoTo", x: 85, y: 59, map: "Stare Ruiny"},
        {ac: "Attack", target: "Szary wilk", map: "Stare Ruiny"},
        {ac: "GoTo", x: 91, y: 60, map: "Stare Ruiny"},
        {ac: "Attack", target: "Szary wilk", map: "Stare Ruiny"},
        {ac: "GoTo", x: 91, y: 57, map: "Stare Ruiny"},
        {ac: "Attack", target: "Szary wilk", map: "Stare Ruiny"},
        {ac: "GoTo", x: 92, y: 48, map: "Stare Ruiny"},
        {ac: "Attack", target: "Szary wilk", map: "Stare Ruiny"},
        {ac: "GoTo", x: 78, y: 41, map: "Stare Ruiny"},
        {ac: "Attack", target: "Szary wilk", map: "Stare Ruiny"},
        {ac: "Reset", number: 0, map: "Stare Ruiny"},
        ]
var Lambo_Respy = [
        {ac: "GoToGate", x: 95, y: 50, map: "Torneg"},
        {ac: "GoToGate", x: 95, y: 57, map: "Leśna Przełęcz"},
        {ac: "GoToGate", x: 29, y: 67, map: "Kryjówka Dzikich Kotów"},
        {ac: "GoToGate", x: 42, y: 27, map: "Jaskinia Dzikich Kotów"},
        {ac: "GoToGate", x:  0, y: 16, map: "Tygrysia Polana"},
        {ac: "GoToGate", x: 54, y:  0, map: "Kryjówka Dzikich Kotów"},
        {ac: "GoToGate", x: 63, y: 59, map: "Osada Mulusów"},
        {ac: "GoTo", x: 46, y: 12, map: "Pradawne Wzgórze Przodków"},
        ]

var Regu_Respy = [
{ac: "GoToGate", x:  6, y:  4, map: "Mokra Grota p.2"},
        {ac: "GoToGate", x:  4, y: 60, map: "Mokra Grota p.1"},
        {ac: "GoToGate", x: 15, y: 53, map: "Zapomniany Szlak"},
        {ac: "GoToGate", x: 24, y: 37, map: "Kamienna Jaskinia"},
        {ac: "GoToGate", x: 26, y: 61, map: "Kamienna Jaskinia - sala 2"},
        {ac: "GoToGate", x:  3, y: 39, map: "Andarum Ilami"},
        {ac: "GoToGate", x: 20, y: 61, map: "Zdradzieckie Przejście - sala wyjściowa"},
        {ac: "GoToGate", x:  3, y: 45, map: "Zdradzieckie Przejście"},
        {ac: "GoToGate", x: 33, y:  2, map: "Pieczara Szaleńców - sala 4"},
        {ac: "GoTo", x: 20, y: 10, map: "Pieczara Szaleńców - przedsionek"},
        {ac: "---------------------------------------------"},
        {ac: "GoToGate", x: 63, y: 54, map: "Werbin"},
        {ac: "GoToGate", x: 13, y: 63, map: "Brama Północy"},
        {ac: "GoToGate", x: 46, y: 95, map: "Góry Zrębowe"},
        {ac: "GoToGate", x: 63, y: 23, map: "Zachodnie Rozdroża"},
        {ac: "GoToGate", x:  46, y: 26, map: "Kanion Straceńców"},
        {ac: "GoToGate", x:   9, y: 40, map: "Krasowa Pieczara p.2"},
        {ac: "GoToGate", x:  10, y: 46, map: "Krasowa Pieczara p.3"},
        {ac: "GoToGate", x:  58, y: 34, map: "Kanion Straceńców"},
        {ac: "GoToGate", x:   7, y:  9, map: "Pieczara Szaleńców - sala 1"},
        {ac: "GoToGate", x:  54, y:  3, map: "Pieczara Szaleńców - sala 2"},
        {ac: "GoToGate", x:  58, y: 35, map: "Pieczara Szaleńców - sala 3"},
        {ac: "GoToGate", x: 33, y:  2, map: "Pieczara Szaleńców - sala 4"},
        {ac: "GoTo", x: 20, y: 10, map: "Pieczara Szaleńców - przedsionek"},
        ]

var Kostek_Respy = [
        {ac: "GoToGate", x: 43, y: 99, map: "Ithan"},
        {ac: "GoToGate", x: 11, y: 63, map: "Zniszczone Opactwo"},
        {ac: "GoToGate", x: 25, y: 63, map: "Zburzona Twierdza"},
        {ac: "GoToGate", x:  0, y: 32, map: "Nawiedzony Jar"},
        {ac: "GoToGate", x: 33, y:  0, map: "Mroczny Przesmyk"},
        {ac: "GoToGate", x: 15, y: 53, map: "Zapomniany Szlak"},
        {ac: "GoToGate", x: 24, y: 37, map: "Kamienna Jaskinia"},
        {ac: "GoToGate", x: 26, y: 61, map: "Kamienna Jaskinia - sala 2"},
        {ac: "GoToGate", x: 3, y:  39, map: "Andarum Ilami"},
        {ac: "GoToGate", x: 20, y: 61, map: "Zdradzieckie Przejście - sala wyjściowa"},
        {ac: "GoTo", x: 65, y: 36, map: "Zdradzieckie Przejście"},
        {ac: "GoTo", x: 21, y:  6, map: "Zdradzieckie Przejście"},
        {ac: "GoTo", x: 22, y:  56, map: "Zdradzieckie Przejście"},
        {ac: "GoToGate", x: 71, y: 61, map: "Zdradzieckie Przejście"},
        {ac: "GoTo", x:  49, y:  24, map: "Labirynt Margorii"},
        {ac: "GoTo", x:  15, y:  38, map: "Labirynt Margorii"},
        {ac: "GoTo", x:  35, y:  18, map: "Labirynt Margorii"},
        {ac: "GoTo", x:  34, y:  46, map: "Labirynt Margorii"},
        {ac: "GoTo", x:  57, y:  55, map: "Labirynt Margorii"},
        {ac: "GoToGate", x: 10, y: 57, map: "Labirynt Margorii"},
        {ac: "GoTo", x:  50, y:  12, map: "Kopalnia Margorii"},
        {ac: "GoTo", x:  11, y:  39, map: "Kopalnia Margorii"},
        {ac: "GoTo", x:  7, y:  49, map: "Kopalnia Margorii"},
        {ac: "GoTo", x:  27, y:  38, map: "Kopalnia Margorii"},
        {ac: "GoTo", x:  30, y:  22, map: "Kopalnia Margorii"},
        {ac: "GoTo", x:  52, y:  40, map: "Kopalnia Margorii"},
        {ac: "GoTo", x:  53, y:  62, map: "Kopalnia Margorii"},
        {ac: "GoToGate", x: 92, y: 34, map: "Kopalnia Margorii"},
        {ac: "GoTo", x:  38, y:  82, map: "Margoria Sala Królewska"},
        {ac: "GoTo", x:  10, y:  77, map: "Margoria Sala Królewska"},
        {ac: "GoTo", x:  24, y:  60, map: "Margoria Sala Królewska"},
        {ac: "GoTo", x:  22, y:  30, map: "Margoria Sala Królewska"},
        {ac: "GoTo", x:  51, y:  24, map: "Margoria Sala Królewska"},
        {ac: "GoToGate", x: 24, y: 92, map: "Margoria Sala Królewska"},
        {ac: "GoToGate", x: 88, y: 12, map: "Kopalnia Margorii"},
        {ac: "GoToGate", x: 58, y: 3, map: "Labirynt Margorii"},
        {ac: "GoTo", x: 56, y: 31, map: "Zdradzieckie Przejście"},
        {ac: "Reset", number: 11, map: "Zdradzieckie Przejście"},
        ]

var Mroczny_Patryk_Respy = [
        {ac: "GoToGate", x: 47, y: 63, map: "Torneg"},
        {ac: "GoToGate", x: 43, y: 63, map: "Stare Ruiny"},
        {ac: "GoTo", x: 56, y:  4, map: "Orla Grań"},
        {ac: "GoTo", x: 28, y:  3, map: "Orla Grań"},
        {ac: "GoTo", x: 19, y: 21, map: "Orla Grań"},
        {ac: "GoToGate", x: 21, y: 40, map: "Orla Grań"},
        {ac: "GoTo", x: 9, y:  15, map: "Spustoszona jaskinia"},
        {ac: "GoToGate", x: 6, y:  21, map: "Spustoszona jaskinia"},
        {ac: "GoTo", x:  2, y: 49, map: "Orla Grań"},
        {ac: "GoTo", x:  7, y: 17, map: "Orla Grań"},
        {ac: "GoTo", x: 14, y:  7, map: "Orla Grań"},
        {ac: "GoTo", x: 19, y: 52, map: "Orla Grań"},
        {ac: "GoTo", x: 19, y: 71, map: "Orla Grań"},
        {ac: "GoTo", x: 31, y: 58, map: "Orla Grań"},
        {ac: "GoTo", x: 52, y: 27, map: "Orla Grań"},
        {ac: "GoTo", x: 58, y: 46, map: "Orla Grań"},
        {ac: "GoTo", x: 57, y: 75, map: "Orla Grań"},
        {ac: "GoTo", x: 48, y: 79, map: "Orla Grań"},
        {ac: "GoTo", x: 10, y: 84, map: "Orla Grań"},
        {ac: "GoToGate", x: 17, y: 95, map: "Orla Grań"},
        {ac: "GoTo", x: 42, y: 11, map: "Przełęcz Łotrzyków"},
        {ac: "GoTo", x: 27, y: 14, map: "Przełęcz Łotrzyków"},
        {ac: "GoTo", x: 40, y: 29, map: "Przełęcz Łotrzyków"},
        {ac: "GoTo", x: 53, y: 38, map: "Przełęcz Łotrzyków"},
        {ac: "GoTo", x: 45, y: 40, map: "Przełęcz Łotrzyków"},
        {ac: "GoTo", x: 46, y: 49, map: "Przełęcz Łotrzyków"},
        {ac: "GoTo", x: 51, y: 62, map: "Przełęcz Łotrzyków"},
        {ac: "GoTo", x: 14, y: 22, map: "Przełęcz Łotrzyków"},
        {ac: "GoTo", x: 14, y: 51, map: "Przełęcz Łotrzyków"},
        {ac: "GoTo", x: 11, y: 62, map: "Przełęcz Łotrzyków"},
        {ac: "GoTo", x: 35, y: 81, map: "Przełęcz Łotrzyków"},
        {ac: "GoTo", x: 44, y: 75, map: "Przełęcz Łotrzyków"},
        {ac: "GoTo", x: 45, y: 84, map: "Przełęcz Łotrzyków"},
        {ac: "GoTo", x: 55, y: 78, map: "Przełęcz Łotrzyków"},
        {ac: "GoTo", x:  6, y: 84, map: "Przełęcz Łotrzyków"},
        {ac: "GoToGate", x: 12, y: 95, map: "Przełęcz Łotrzyków"},
        {ac: "GoTo", x: 11, y:  5, map: "Dolina Rozbójników"},
        {ac: "GoTo", x: 18, y:  2, map: "Dolina Rozbójników"},
        {ac: "GoTo", x: 41, y: 11, map: "Dolina Rozbójników"},
        {ac: "GoTo", x: 28, y: 23, map: "Dolina Rozbójników"},
        {ac: "GoTo", x: 37, y: 24, map: "Dolina Rozbójników"},
        {ac: "GoTo", x: 39, y: 19, map: "Dolina Rozbójników"},
        {ac: "GoTo", x: 47, y: 19, map: "Dolina Rozbójników"},
        {ac: "GoToGate", x: 63, y: 19, map: "Dolina Rozbójników"},
        {ac: "GoTo", x: 11, y: 19, map: "Wioska Ghuli"},
        {ac: "GoTo", x: 30, y:  2, map: "Wioska Ghuli"},
        {ac: "GoTo", x: 60, y:  3, map: "Wioska Ghuli"},
        {ac: "GoTo", x: 49, y: 20, map: "Wioska Ghuli"},
        {ac: "GoTo", x: 23, y: 27, map: "Wioska Ghuli"},
        {ac: "GoTo", x: 31, y: 13, map: "Wioska Ghuli"},
        {ac: "GoTo", x: 12, y: 47, map: "Wioska Ghuli"},
        {ac: "GoTo", x: 18, y: 58, map: "Wioska Ghuli"},
        {ac: "GoTo", x: 42, y: 55, map: "Wioska Ghuli"},
        {ac: "GoToGate", x: 29, y: 63, map: "Wioska Ghuli"},
        {ac: "GoTo", x:  5, y: 27, map: "Polana Ścierwojadów"},
        {ac: "GoTo", x: 47, y: 52, map: "Polana Ścierwojadów"},
        {ac: "GoTo", x: 37, y: 24, map: "Polana Ścierwojadów"},
        {ac: "GoTo", x: 53, y: 11, map: "Polana Ścierwojadów"},
        {ac: "GoToGate", x: 30, y:  0, map: "Polana Ścierwojadów"},
        {ac: "GoToGate", x:  0, y: 19, map: "Wioska Ghuli"},
        {ac: "GoTo", x: 21, y: 29, map: "Dolina Rozbójników"},
        {ac: "GoTo", x: 20, y: 36, map: "Dolina Rozbójników"},
        {ac: "GoTo", x: 29, y: 40, map: "Dolina Rozbójników"},
        {ac: "GoTo", x: 37, y: 49, map: "Dolina Rozbójników"},
        {ac: "GoTo", x: 17, y: 49, map: "Dolina Rozbójników"},
        {ac: "GoTo", x:  8, y: 44, map: "Dolina Rozbójników"},
        {ac: "GoTo", x: 12, y: 57, map: "Dolina Rozbójników"},
        {ac: "GoTo", x: 14, y: 70, map: "Dolina Rozbójników"},
        {ac: "GoTo", x: 15, y: 82, map: "Dolina Rozbójników"},
        {ac: "GoTo", x: 23, y: 91, map: "Dolina Rozbójników"},
        {ac: "GoTo", x: 41, y: 76, map: "Dolina Rozbójników"},
        {ac: "GoTo", x: 33, y: 68, map: "Dolina Rozbójników"},
        {ac: "GoTo", x: 41, y: 57, map: "Dolina Rozbójników"},
        {ac: "GoTo", x: 45, y: 66, map: "Dolina Rozbójników"},
        {ac: "GoTo", x: 54, y: 42, map: "Dolina Rozbójników"},
        {ac: "GoToGate", x: 26, y: 95, map: "Dolina Rozbójników"},
        {ac: "GoTo", x: 19, y:  6, map: "Mokradła"},
        {ac: "GoTo", x: 20, y: 11, map: "Mokradła"},
        {ac: "GoTo", x: 58, y: 13, map: "Mokradła"},
        {ac: "GoTo", x: 54, y: 31, map: "Mokradła"},
        {ac: "GoTo", x: 53, y: 46, map: "Mokradła"},
        {ac: "GoTo", x: 47, y: 54, map: "Mokradła"},
        {ac: "GoTo", x: 44, y: 46, map: "Mokradła"},
        {ac: "GoTo", x: 34, y: 44, map: "Mokradła"},
        {ac: "GoTo", x: 26, y: 45, map: "Mokradła"},
        {ac: "GoTo", x: 24, y: 36, map: "Mokradła"},
        {ac: "GoTo", x:  8, y: 43, map: "Mokradła"},
        {ac: "GoTo", x:  4, y: 46, map: "Mokradła"},
        {ac: "GoTo", x:  9, y: 50, map: "Mokradła"},
        {ac: "GoTo", x:  8, y: 53, map: "Mokradła"},
        {ac: "GoToGate", x:  0, y: 39, map: "Mokradła"},
        {ac: "GoTo", x: 42, y:  4, map: "Podmokła Dolina"},
        {ac: "GoToGate", x: 32, y:  0, map: "Podmokła Dolina"},
        {ac: "GoTo", x:  8, y: 62, map: "Morwowe Przejście"},
        {ac: "GoTo", x:  4, y: 51, map: "Morwowe Przejście"},
        {ac: "GoTo", x: 52, y: 40, map: "Morwowe Przejście"},
        {ac: "GoTo", x: 55, y:  8, map: "Morwowe Przejście"},
        {ac: "GoTo", x: 46, y: 19, map: "Morwowe Przejście"},
        {ac: "GoTo", x: 31, y: 24, map: "Morwowe Przejście"},
        {ac: "GoToGate", x: 32, y: 63, map: "Morwowe Przejście"},
        {ac: "GoTo", x: 54, y: 56, map: "Podmokła Dolina"},
        {ac: "GoToGate", x: 43, y: 63, map: "Podmokła Dolina"},
        {ac: "GoTo", x: 20, y:  9, map: "Las Goblinów"},
        {ac: "GoTo", x:  8, y: 18, map: "Las Goblinów"},
        {ac: "GoTo", x: 17, y: 35, map: "Las Goblinów"},
        {ac: "GoTo", x:  7, y: 37, map: "Las Goblinów"},
        {ac: "GoTo", x: 55, y: 10, map: "Las Goblinów"},
        {ac: "GoTo", x: 52, y: 21, map: "Las Goblinów"},
        {ac: "GoTo", x: 37, y: 27, map: "Las Goblinów"},
        {ac: "GoTo", x: 36, y: 45, map: "Las Goblinów"},
        {ac: "GoTo", x: 46, y: 38, map: "Las Goblinów"},
        {ac: "GoTo", x: 51, y: 46, map: "Las Goblinów"},
        {ac: "GoTo", x: 22, y: 81, map: "Las Goblinów"},
        {ac: "GoTo", x: 32, y: 87, map: "Las Goblinów"},
        {ac: "GoTo", x: 33, y: 78, map: "Las Goblinów"},
        {ac: "GoTo", x:  4, y: 87, map: "Las Goblinów"},
        {ac: "GoTo", x:  6, y: 80, map: "Las Goblinów"},
        {ac: "GoToGate", x: 42, y:  0, map: "Las Goblinów"},
        {ac: "GoToGate", x: 63, y: 39, map: "Podmokła Dolina"},
        {ac: "GoToGate", x: 27, y:  0, map: "Mokradła"},
        {ac: "GoToGate", x: 11, y:  0, map: "Dolina Rozbójników"},
        {ac: "GoToGate", x: 17, y:  0, map: "Przełęcz Łotrzyków"},
        {ac: "GoTo", x: 43, y:  7, map: "Orla Grań"},
        {ac: "Reset", number: 2, map: "Orla Grań"},
        {ac: "------------------------------------"},
        ]

var Karmazynowy_Msciciel_Respy = [
        {ac: "GoToGate", x: 63, y: 53, map: "Werbin"},
        {ac: "GoToGate", x: 13, y: 63, map: "Brama Północy"},
        {ac: "GoTo", x: 10, y:  7, map: "Góry Zrębowe"},
        {ac: "GoTo", x: 40, y: 11, map: "Góry Zrębowe"},
        {ac: "GoToGate", x: 39, y:  7, map: "Góry Zrębowe"},
        {ac: "GoToGate", x: 12, y:  7, map: "Solna Grota p.1"},
        {ac: "GoTo", x: 16, y:  9, map: "Solna Grota p.2"},
        {ac: "GoToGate", x: 26, y:  2, map: "Solna Grota p.2"},
        {ac: "GoToGate", x:  4, y: 11, map: "Solna Grota p.1"},
        {ac: "GoTo", x:  40, y: 26, map: "Góry Zrębowe"},
        {ac: "GoTo", x:   2, y: 56, map: "Góry Zrębowe"},
        {ac: "GoTo", x:  51, y: 92, map: "Góry Zrębowe"},
        {ac: "GoTo", x:  53, y: 70, map: "Góry Zrębowe"},
        {ac: "GoToGate", x:  46, y: 95, map: "Góry Zrębowe"},
        {ac: "GoTo", x:  15, y: 18, map: "Zachodnie Rozdroża"},
        {ac: "GoToGate", x:  23, y: 6, map: "Zachodnie Rozdroża"},
        {ac: "GoToGate", x:  19, y:18, map: "Przepastna Grota p.1"},
        {ac: "GoTo", x:  19, y: 7, map: "Przepastna Grota p.2"},
        {ac: "GoToGate", x:  18, y:19, map: "Przepastna Grota p.2"},
        {ac: "GoToGate", x:   4, y:10, map: "Przepastna Grota p.1"},
        {ac: "GoTo", x:  50, y: 20, map: "Zachodnie Rozdroża"},
        {ac: "GoToGate", x:  50, y: 17, map: "Zachodnie Rozdroża"},
        {ac: "GoToGate", x:  11, y: 12, map: "Pieczara Wiatru p.1"},
        {ac: "GoToGate", x:  15, y: 29, map: "Pieczara Wiatru p.2"},
        {ac: "GoTo", x:   9, y: 12, map: "Pieczara Wiatru p.3"},
        {ac: "GoToGate", x:  19, y:  9, map: "Pieczara Wiatru p.3"},
        {ac: "GoToGate", x:  17, y:  7, map: "Pieczara Wiatru p.2"},
        {ac: "GoToGate", x:  13, y: 19, map: "Pieczara Wiatru p.1"},
        {ac: "GoToGate", x:  63, y: 24, map: "Zachodnie Rozdroża"},
        {ac: "GoToGate", x:  46, y: 26, map: "Kanion Straceńców"},
        {ac: "GoToGate", x:   7, y:  5, map: "Krasowa Pieczara p.2"},
        {ac: "GoToGate", x:   7, y: 14, map: "Krasowa Pieczara p.1"},
        {ac: "GoTo", x:  47, y:  5, map: "Kanion Straceńców"},
        {ac: "GoToGate", x:  12, y:  5, map: "Kanion Straceńców"},
        {ac: "GoToGate", x:   8, y:  7, map: "Krasowa Pieczara p.1"},
        {ac: "GoToGate", x:   9, y: 40, map: "Krasowa Pieczara p.2"},
        {ac: "GoToGate", x:  10, y: 46, map: "Krasowa Pieczara p.3"},
        {ac: "GoTo", x:  40, y: 54, map: "Kanion Straceńców"},
        {ac: "GoToGate", x:  58, y: 34, map: "Kanion Straceńców"},
        {ac: "GoToGate", x:   7, y:  9, map: "Pieczara Szaleńców - sala 1"},
        {ac: "GoToGate", x:  54, y:  3, map: "Pieczara Szaleńców - sala 2"},
        {ac: "GoToGate", x:  58, y: 35, map: "Pieczara Szaleńców - sala 3"},
        {ac: "GoToGate", x:   5, y: 21, map: "Pieczara Szaleńców - sala 4"},
        {ac: "GoTo", x:  14, y: 10, map: "Kanion Szaleńców"},
        {ac: "GoTo", x:  38, y:  8, map: "Kanion Szaleńców"},
        {ac: "GoTo", x:  59, y: 12, map: "Kanion Szaleńców"},
        {ac: "GoTo", x:  32, y: 38, map: "Kanion Szaleńców"},
        {ac: "GoTo", x:  11, y: 38, map: "Kanion Szaleńców"},
        {ac: "GoTo", x:  56, y: 56, map: "Kanion Szaleńców"},
        {ac: "GoToGate", x:  27, y: 28, map: "Kanion Szaleńców"},
        {ac: "GoToGate", x:  43, y: 44, map: "Pieczara Szaleńców - sala 4"},
        {ac: "GoToGate", x:  11, y:  6, map: "Pieczara Szaleńców - sala 3"},
        {ac: "GoToGate", x:   6, y: 30, map: "Pieczara Szaleńców - sala 2"},
        {ac: "GoToGate", x:  22, y: 45, map: "Pieczara Szaleńców - sala 1"},
        {ac: "GoToGate", x:  19, y: 40, map: "Kanion Straceńców"},
        {ac: "GoToGate", x:   9, y: 13, map: "Krasowa Pieczara p.3"},
        {ac: "GoToGate", x:  35, y: 41, map: "Krasowa Pieczara p.2"},
        {ac: "GoToGate", x:   0, y: 23, map: "Kanion Straceńców"},
        {ac: "GoTo", x:  7, y: 60, map: "Zachodnie Rozdroża"},
        {ac: "GoTo", x: 46, y: 57, map: "Zachodnie Rozdroża"},
        {ac: "GoTo", x: 41, y: 87, map: "Zachodnie Rozdroża"},
        {ac: "GoTo", x:  7, y: 88, map: "Zachodnie Rozdroża"},
        {ac: "GoToGate", x: 17, y: 95, map: "Zachodnie Rozdroża"},
        {ac: "GoToGate", x: 55, y: 44, map: "Cienisty Bór"},
        {ac: "GoToGate", x:  9, y:  7, map: "Barwna Jaskinia p.1"},
        {ac: "GoTo", x: 47, y: 27, map: "Barwna Jaskinia p.2"},
        {ac: "GoToGate", x:  5, y: 30, map: "Barwna Jaskinia p.2"},
        {ac: "GoTo", x: 12, y: 37, map: "Cienisty Bór"},
        {ac: "GoTo", x: 14, y: 70, map: "Cienisty Bór"},
        {ac: "GoToGate", x: 42, y: 95, map: "Cienisty Bór"},
        {ac: "GoTo", x: 21, y: 15, map: "Las Dziwów"},
        {ac: "GoTo", x:  9, y: 67, map: "Las Dziwów"},
        {ac: "GoTo", x: 35, y: 80, map: "Las Dziwów"},
        {ac: "GoToGate", x: 42, y:  0, map: "Las Dziwów"},
        {ac: "GoToGate", x: 17, y:  0, map: "Cienisty Bór"},
        {ac: "GoToGate", x: 46, y:  0, map: "Zachodnie Rozdroża"},
        {ac: "GoTo", x: 46, y: 91, map: "Góry Zrębowe"},
        {ac: "Reset", number: 2, map: "Góry Zrębowe"}
        ]

    var Zlodziej_Respy = [
        {ac: "GoTo", x:  47, y: 53, map: "Eder"},
        {ac: "GoToGate", x:  50, y: 57, map: "Eder"},
        {ac: "GoToGate", x:  11, y:  8, map: "Dom Erniego"},
        {ac: "GoTo", x:  11, y:  5, map: "Dom Erniego p.1"},
        {ac: "GoToGate", x:  11, y:  7, map: "Dom Erniego p.1"},
        {ac: "GoToGate", x:   2, y:  8, map: "Dom Erniego"},
        {ac: "GoToGate", x:  57, y: 40, map: "Eder"},
        {ac: "GoToGate", x:   4, y: 12, map: "Dom Etrefana"},
        {ac: "GoTo", x:   3, y:  8, map: "Dom Etrefana - pracownia"},
        {ac: "GoToGate", x:   2, y:  3, map: "Dom Etrefana - pracownia"},
        {ac: "GoToGate", x:  11, y:  9, map: "Dom Etrefana"},
        {ac: "GoToGate", x:  11, y:  9, map: "Dom Etrefana p.1"},
        {ac: "GoTo", x:  10, y:  5, map: "Dom Etrefana p.2"},
        {ac: "GoToGate", x:  11, y:  7, map: "Dom Etrefana p.2"},
        {ac: "GoToGate", x:  11, y:  7, map: "Dom Etrefana p.1"},
        {ac: "GoToGate", x:   7, y: 13, map: "Dom Etrefana"},
        {ac: "GoToGate", x:  47, y: 24, map: "Eder"},
        {ac: "GoToGate", x:  11, y:  5, map: "Dom Artenii i Tafina"},
        {ac: "GoTo", x:  11, y: 12, map: "Dom Artenii i Tafina - piwnica"},
        {ac: "GoToGate", x:   2, y:  2, map: "Dom Artenii i Tafina - piwnica"},
        {ac: "GoToGate", x:   8, y: 12, map: "Dom Artenii i Tafina"},
        {ac: "GoToGate", x:  40, y: 32, map: "Eder"},
        {ac: "GoToGate", x:   8, y: 11, map: "Dom Mikliniosa"},
        {ac: "GoTo", x:  10, y:  7, map: "Dom Mikliniosa - przyziemie"},
        {ac: "GoToGate", x:  10, y:  5, map: "Dom Mikliniosa - przyziemie"},
        {ac: "GoToGate", x:  12, y:  7, map: "Dom Mikliniosa"},
        {ac: "GoTo", x:  10, y:  5, map: "Dom Mikliniosa p.1"},
        {ac: "GoToGate", x:  12, y:  6, map: "Dom Mikliniosa p.1"},
        {ac: "GoToGate", x:   3, y:  8, map: "Dom Mikliniosa"},
        {ac: "GoToGate", x:  41, y: 40, map: "Eder"},
        {ac: "GoToGate", x:  11, y:  8, map: "Pracownia Bonifacego"},
        {ac: "GoTo", x:  10, y:  9, map: "Pracownia Bonifacego p.1"},
        {ac: "GoToGate", x:  10, y: 11, map: "Pracownia Bonifacego p.1"},
        {ac: "GoToGate", x:   7, y: 12, map: "Pracownia Bonifacego"},
        {ac: "GoToGate", x:   3, y:  6, map: "Eder"},
        {ac: "GoTo", x:   8, y: 11, map: "Dom Mrocznego Zgrzyta"},
        {ac: "GoToGate", x:   8, y: 13, map: "Dom Mrocznego Zgrzyta"},
        {ac: "GoToGate", x:  31, y: 12, map: "Eder"},
        {ac: "GoTo", x:  11, y: 11, map: "Siedziba Kultystów"},
        {ac: "GoToGate", x:  15, y: 28, map: "Siedziba Kultystów"},
        {ac: "GoToGate", x:  28, y:  0, map: "Eder"},
        {ac: "GoToGate", x:  24, y: 73, map: "Fort Eder"},
        {ac: "GoToGate", x:  17, y: 17, map: "Fortyfikacja p.1"},
        {ac: "GoTo", x:   7, y: 17, map: "Fortyfikacja"},
        {ac: "GoToGate", x:  16, y: 14, map: "Fortyfikacja"},
        {ac: "GoToGate", x:   8, y: 11, map: "Fortyfikacja p.1"},
        {ac: "GoToGate", x:  12, y:  1, map: "Fortyfikacja p.2"},
        {ac: "GoToGate", x:   6, y:  1, map: "Fortyfikacja p.3"},
        {ac: "GoToGate", x:  13, y:  1, map: "Fortyfikacja p.4"},
        {ac: "GoTo", x:   9, y:  8, map: "Fortyfikacja p.5"},
        {ac: "GoToGate", x:  13, y:  5, map: "Fortyfikacja p.5"},
        {ac: "GoToGate", x:   6, y:  9, map: "Fortyfikacja p.4"},
        {ac: "GoToGate", x:  13, y:  5, map: "Fortyfikacja p.3"},
        {ac: "GoToGate", x:   8, y: 12, map: "Fortyfikacja p.2"},
        {ac: "GoToGate", x:  13, y: 18, map: "Fortyfikacja p.1"},
        {ac: "GoToGate", x:  60, y: 83, map: "Fort Eder"},
        {ac: "GoTo", x:   8, y: 13, map: "Ciemnica Szubrawców p.1 - sala 1"},
        {ac: "GoToGate", x:   6, y: 40, map: "Ciemnica Szubrawców p.1 - sala 1"},
        {ac: "GoTo", x:  13, y:  5, map: "Ciemnica Szubrawców p.1 - sala 2"},
        {ac: "GoToGate", x:  36, y: 39, map: "Ciemnica Szubrawców p.1 - sala 2"},
        {ac: "GoTo", x:  42, y: 12, map: "Ciemnica Szubrawców p.1 - sala 3"},
        {ac: "GoTo", x:  51, y: 53, map: "Ciemnica Szubrawców p.1 - sala 3"},
        {ac: "GoToGate", x:   8, y:  4, map: "Ciemnica Szubrawców p.1 - sala 3"},
        {ac: "GoToGate", x:   2, y:  7, map: "Ciemnica Szubrawców p.1 - sala 2"},
        {ac: "GoToGate", x:   2, y: 10, map: "Ciemnica Szubrawców p.1 - sala 1"},
        {ac: "GoTo", x:  59, y: 60, map: "Fort Eder"},
        {ac: "GoTo", x:  57, y: 68, map: "Fort Eder"},
        {ac: "GoToGate", x:  63, y: 53, map: "Fort Eder"},
        {ac: "GoTo", x:   8, y:  8, map: "Stary Kupiecki Trakt"},
        {ac: "GoTo", x:  51, y: 12, map: "Stary Kupiecki Trakt"},
        {ac: "GoTo", x:  55, y: 44, map: "Stary Kupiecki Trakt"},
        {ac: "GoTo", x:  55, y: 92, map: "Stary Kupiecki Trakt"},
        {ac: "GoToGate", x:  31, y: 95, map: "Stary Kupiecki Trakt"},
        {ac: "GoTo", x:  20, y: 28, map: "Stukot Widmowych Kół"},
        {ac: "GoTo", x:   5, y:  5, map: "Stukot Widmowych Kół"},
        {ac: "GoTo", x:  23, y: 61, map: "Stukot Widmowych Kół"},
        {ac: "GoTo", x:   8, y: 61, map: "Stukot Widmowych Kół"},
        {ac: "GoTo", x:  48, y: 72, map: "Stukot Widmowych Kół"},
        {ac: "GoToGate", x:  18, y: 95, map: "Stukot Widmowych Kół"},
        {ac: "GoTo", x:  12, y: 55, map: "Wertepy Rzezimieszków"},
        {ac: "GoTo", x:  53, y: 51, map: "Wertepy Rzezimieszków"},
        {ac: "GoTo", x:  55, y: 12, map: "Wertepy Rzezimieszków"},
        {ac: "GoToGate", x:  49, y:  9, map: "Wertepy Rzezimieszków"},
        {ac: "GoTo", x:   6, y:  4, map: "Chata szabrowników"},
        {ac: "GoToGate", x:   7, y: 14, map: "Chata szabrowników"},
        {ac: "GoToGate", x:  18, y:  0, map: "Wertepy Rzezimieszków"},
        {ac: "GoToGate", x:  32, y:  0, map: "Stukot Widmowych Kół"},
        {ac: "GoToGate", x:   0, y: 22, map: "Stary Kupiecki Trakt"},
        {ac: "GoToGate", x:  27, y: 95, map: "Fort Eder"},
        {ac: "GoTo", x:  22, y:  6, map: "Eder"},
        {ac: "Reset", number: 0, map: "Eder"}
    ]

    var Zly_Przewodnik_Respy = [
        {ac: "GoToGate", x:  43, y: 99, map: "Ithan"},
        {ac: "GoToGate", x:  11, y: 63, map: "Zniszczone Opactwo"},
        {ac: "GoTo", x:  31, y:  5, map: "Zburzona Twierdza"},
        {ac: "GoTo", x:  12, y: 18, map: "Zburzona Twierdza"},
        {ac: "GoTo", x:  13, y: 42, map: "Zburzona Twierdza"},
        {ac: "GoTo", x:  53, y: 44, map: "Zburzona Twierdza"},
        {ac: "GoTo", x:  52, y: 33, map: "Zburzona Twierdza"},
        {ac: "GoTo", x:  41, y: 37, map: "Zburzona Twierdza"},
        {ac: "GoToGate", x:  25, y: 63, map: "Zburzona Twierdza"},
        {ac: "GoTo", x:   5, y: 11, map: "Nawiedzony Jar"},
        {ac: "GoToGate", x:  35, y: 25, map: "Nawiedzony Jar"},
        {ac: "GoToGate", x:  23, y: 29, map: "Stare Wyrobisko p.4"},
        {ac: "GoToGate", x:  11, y: 29, map: "Stare Wyrobisko p.3"},
        {ac: "GoTo", x:  38, y: 19, map: "Nawiedzony Jar"},
        {ac: "GoTo", x:  54, y: 32, map: "Nawiedzony Jar"},
        {ac: "GoToGate", x:  42, y: 24, map: "Nawiedzony Jar"},
        {ac: "GoToGate", x:   6, y: 22, map: "Stare Wyrobisko p.3"},
        {ac: "GoToGate", x:  13, y: 48, map: "Stare Wyrobisko p.4"},
        {ac: "GoToGate", x:   0, y: 32, map: "Nawiedzony Jar"},
        {ac: "GoTo", x:  58, y: 29, map: "Mroczny Przesmyk"},
        {ac: "GoTo", x:  29, y: 56, map: "Mroczny Przesmyk"},
        {ac: "GoTo", x:  17, y: 52, map: "Mroczny Przesmyk"},
        {ac: "GoTo", x:  26, y: 27, map: "Mroczny Przesmyk"},
        {ac: "GoTo", x:  23, y:  8, map: "Mroczny Przesmyk"},
        {ac: "GoTo", x:  39, y:  2, map: "Mroczny Przesmyk"},
        {ac: "GoToGate", x:  33, y:  0, map: "Mroczny Przesmyk"},
        {ac: "GoTo", x:  86, y: 50, map: "Zapomniany Szlak"},
        {ac: "GoTo", x:  47, y: 16, map: "Zapomniany Szlak"},
        {ac: "GoTo", x:  21, y: 15, map: "Zapomniany Szlak"},
        {ac: "GoTo", x:  12, y: 34, map: "Zapomniany Szlak"},
        {ac: "GoTo", x:  24, y: 51, map: "Zapomniany Szlak"},
        {ac: "GoToGate", x:  15, y: 53, map: "Zapomniany Szlak"},
        {ac: "GoToGate", x:  24, y: 37, map: "Kamienna Jaskinia"},
        {ac: "GoToGate", x:  26, y: 61, map: "Kamienna Jaskinia - sala 2"},
        {ac: "GoTo", x:  53, y: 28, map: "Andarum Ilami"},
        {ac: "GoTo", x:  33, y:  7, map: "Andarum Ilami"},
        {ac: "GoTo", x:  22, y: 21, map: "Andarum Ilami"},
        {ac: "GoTo", x:  12, y:  8, map: "Andarum Ilami"},
        {ac: "GoTo", x:  16, y: 43, map: "Andarum Ilami"},
        {ac: "GoToGate", x:  58, y: 52, map: "Andarum Ilami"},
        {ac: "GoToGate", x:  26, y:  4, map: "Kamienna Jaskinia - sala 2"},
        {ac: "GoToGate", x:  25, y:  8, map: "Kamienna Jaskinia"},
        {ac: "GoToGate", x:  65, y: 63, map: "Zapomniany Szlak"},
        {ac: "GoToGate", x:  63, y: 32, map: "Mroczny Przesmyk"},
        {ac: "GoToGate", x:  25, y:  0, map: "Nawiedzony Jar"},
        {ac: "GoTo", x:  23, y: 57, map: "Zburzona Twierdza"},
        {ac: "Reset", number: 8, map: "Zburzona Twierdza"}
    ]

    var Opetany_Paladyn_Respy = [
        {ac: "GoToGate", x:  43, y: 99, map: "Ithan"},
        {ac: "GoToGate", x:  11, y: 63, map: "Zniszczone Opactwo"},
        {ac: "GoToGate", x:  25, y: 63, map: "Zburzona Twierdza"},
        {ac: "GoToGate", x:   0, y: 32, map: "Nawiedzony Jar"},
        {ac: "GoToGate", x:  33, y:  0, map: "Mroczny Przesmyk"},
        {ac: "GoToGate", x:  15, y: 53, map: "Zapomniany Szlak"},
        {ac: "GoToGate", x:  24, y: 37, map: "Kamienna Jaskinia"},
        {ac: "GoToGate", x:  26, y: 61, map: "Kamienna Jaskinia - sala 2"},
        {ac: "GoToGate", x:  48, y: 14, map: "Andarum Ilami"},

        {ac: "GoTo", x:  14, y: 23, map: "Świątynia Andarum"},
        {ac: "GoTo", x:  31, y: 13, map: "Świątynia Andarum"},
        {ac: "GoToGate", x:  40, y: 18, map: "Świątynia Andarum"},
        {ac: "GoTo", x:  20, y: 28, map: "Zejście prawe Świątyni"},
        {ac: "GoToGate", x:  20, y: 32, map: "Zejście prawe Świątyni"},
        {ac: "GoTo", x:  51, y: 31, map: "Podziemia Świątyni"},
        {ac: "GoTo", x:  28, y:  9, map: "Podziemia Świątyni"},
        {ac: "GoToGate", x:   3, y:  1, map: "Podziemia Świątyni"},
        {ac: "GoTo", x:  14, y: 28, map: "Zejście lewe Świątyni"},
        {ac: "GoToGate", x:   4, y: 32, map: "Zejście lewe Świątyni"},
        {ac: "GoToGate", x:  29, y: 34, map: "Podziemia Świątyni"},
        {ac: "GoTo", x:  15, y: 26, map: "Magazyn Świątyni"},
        {ac: "GoTo", x:  54, y: 11, map: "Magazyn Świątyni"},
        {ac: "GoTo", x:  80, y:  8, map: "Magazyn Świątyni"},
        {ac: "GoTo", x:  78, y: 25, map: "Magazyn Świątyni"},
        {ac: "GoTo", x:  76, y: 61, map: "Magazyn Świątyni"},
        {ac: "GoTo", x:  33, y: 45, map: "Magazyn Świątyni"},
        {ac: "GoToGate", x:  47, y: 51, map: "Magazyn Świątyni"},
        {ac: "GoTo", x:  25, y: 55, map: "Magazyn Świątyni p.2"},
        {ac: "GoToGate", x:  13, y: 56, map: "Magazyn Świątyni p.2"},
        {ac: "GoTo", x:  25, y: 59, map: "Zbrojownia Andarum"},
        {ac: "GoTo", x:   7, y: 35, map: "Zbrojownia Andarum"},
        {ac: "GoTo", x:   7, y: 20, map: "Zbrojownia Andarum"},
        {ac: "GoToGate", x:  15, y: 51, map: "Zbrojownia Andarum"},
        {ac: "GoTo", x:  17, y: 41, map: "Magazyn Świątyni p.2"},
        {ac: "GoTo", x:  22, y: 21, map: "Magazyn Świątyni p.2"},
        {ac: "GoTo", x:  50, y: 21, map: "Magazyn Świątyni p.2"},
        {ac: "Attack", target: "Strażnik biblioteki", map: "Magazyn Świątyni p.2"},
        {ac: "GoToGate", x:  50, y: 23, map: "Magazyn Świątyni p.2"},
        {ac: "GoTo", x:  45, y: 57, map: "Biblioteka Andarum"},
        {ac: "GoTo", x:  19, y: 38, map: "Biblioteka Andarum"},
        {ac: "GoTo", x:  19, y: 11, map: "Biblioteka Andarum"},
        {ac: "GoToGate", x:  55, y: 21, map: "Biblioteka Andarum"},
        {ac: "Attack", target: "Strażnik biblioteki", map: "Magazyn Świątyni p.2"},
        {ac: "GoTo", x:  59, y: 35, map: "Magazyn Świątyni p.2"},
        {ac: "GoTo", x:  87, y:  5, map: "Magazyn Świątyni p.2"},
        {ac: "GoToGate", x:  80, y: 16, map: "Magazyn Świątyni p.2"},
        {ac: "GoTo", x:   6, y: 58, map: "Krypta Świątyni Andarum"},
        {ac: "GoTo", x:  40, y: 31, map: "Krypta Świątyni Andarum"},
        {ac: "GoTo", x:   4, y: 16, map: "Krypta Świątyni Andarum"},
        {ac: "GoToGate", x:  32, y: 36, map: "Krypta Świątyni Andarum"},
        {ac: "GoTo", x:  92, y: 54, map: "Magazyn Świątyni p.2"},
        {ac: "GoToGate", x:  47, y: 46, map: "Magazyn Świątyni p.2"},
        {ac: "GoToGate", x:  47, y: 18, map: "Magazyn Świątyni"},
        {ac: "GoToGate", x:  54, y:  1, map: "Podziemia Świątyni"},
        {ac: "GoToGate", x:   8, y:  1, map: "Zejście prawe Świątyni"},
        {ac: "GoToGate", x:  23, y: 19, map: "Świątynia Andarum"},
        {ac: "GoTo", x:  49, y: 22, map: "Andarum Ilami"},
        {ac: "GoToGate", x:  48, y: 14, map: "Andarum Ilami"},
        {ac: "GoTo", x:  22, y: 16, map: "Świątynia Andarum"},
        {ac: "Reset", number: 9, map: "Świątynia Andarum"}
        ]

    var Regulus_dojscie = [
        {ac: "GoToGate", x:  6, y:  4, map: "Mokra Grota p.2"},
        {ac: "GoToGate", x:  4, y: 60, map: "Mokra Grota p.1"},
        {ac: "GoToGate", x: 15, y: 53, map: "Zapomniany Szlak"},
        {ac: "GoToGate", x: 24, y: 37, map: "Kamienna Jaskinia"},
        {ac: "GoToGate", x: 26, y: 61, map: "Kamienna Jaskinia - sala 2"},
        {ac: "GoToGate", x:  3, y: 39, map: "Andarum Ilami"},
        {ac: "GoToGate", x: 20, y: 61, map: "Zdradzieckie Przejście - sala wyjściowa"},
        {ac: "GoToGate", x:  3, y: 45, map: "Zdradzieckie Przejście"},
        {ac: "GoToGate", x: 33, y:  2, map: "Pieczara Szaleńców - sala 4"},
        {ac: "GoTo", x: 20, y: 10, map: "Pieczara Szaleńców - przedsionek"},
        {ac: "---------------------------------------------"},
        {ac: "GoToGate", x: 63, y: 54, map: "Werbin"},
        {ac: "GoToGate", x: 13, y: 63, map: "Brama Północy"},
        {ac: "GoToGate", x: 46, y: 95, map: "Góry Zrębowe"},
        {ac: "GoToGate", x: 63, y: 23, map: "Zachodnie Rozdroża"},
        {ac: "GoToGate", x:  46, y: 26, map: "Kanion Straceńców"},
        {ac: "GoToGate", x:   9, y: 40, map: "Krasowa Pieczara p.2"},
        {ac: "GoToGate", x:  10, y: 46, map: "Krasowa Pieczara p.3"},
        {ac: "GoToGate", x:  58, y: 34, map: "Kanion Straceńców"},
        {ac: "GoToGate", x:   7, y:  9, map: "Pieczara Szaleńców - sala 1"},
        {ac: "GoToGate", x:  54, y:  3, map: "Pieczara Szaleńców - sala 2"},
        {ac: "GoToGate", x:  58, y: 35, map: "Pieczara Szaleńców - sala 3"},
        {ac: "GoToGate", x: 33, y:  2, map: "Pieczara Szaleńców - sala 4"},
        {ac: "GoTo", x: 20, y: 10, map: "Pieczara Szaleńców - przedsionek"},
        ]

    var Lambo_dojscie = [
        {ac: "GoToGate", x: 95, y: 50, map: "Torneg"},
        {ac: "GoToGate", x: 95, y: 57, map: "Leśna Przełęcz"},
        {ac: "GoToGate", x: 29, y: 67, map: "Kryjówka Dzikich Kotów"},
        {ac: "GoToGate", x: 42, y: 27, map: "Jaskinia Dzikich Kotów"},
        {ac: "GoToGate", x:  0, y: 16, map: "Tygrysia Polana"},
        {ac: "GoToGate", x: 54, y:  0, map: "Kryjówka Dzikich Kotów"},
        {ac: "GoToGate", x: 63, y: 59, map: "Osada Mulusów"},
        {ac: "GoTo", x: 46, y: 12, map: "Pradawne Wzgórze Przodków"},
        ]
